"""

https://opentdb.com/api_config.php is used for generating questions.

question_data = [
{"text": "A slug"s blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called "Backrub".", "answer": "True"},
{"text": "Buzz Aldrin"s mother"s maiden name was "Moon".", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]


movies = [{"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which of the following is NOT a quote from the 1942 film Casablanca? ",
           "correct_answer": ""Frankly, my dear, I dont give a damn."",
           "incorrect_answers": [""Heres lookin at you, kid."",
                                 "&ldquoOf all the gin joints, in all the towns, in all the world, she walks into mine&hellip&rdquo",
                                 ""Round up the usual suspects.""]},

          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In the movie &ldquoThe Iron Giant,&rdquo this character is the protagonist.",
           "correct_answer": "Hogarth Hughes", "incorrect_answers": ["Kent Mansley", "Dean McCoppin", "Annie Hughes"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which 1958 movie starred Kirk Douglas and Tony Curtis as half-brothers Einar and Eric?",
           "correct_answer": "The Vikings ", "incorrect_answers": ["The Long Ships", "Prince Valiant", "Spartacus"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which retired American football quarterback played himself in Ace Ventura: Pet Detective and Little Nicky?",
           "correct_answer": "Dan Marino", "incorrect_answers": ["John Elway", "Tom Brady", "Joe Montana"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What was Marilyn Monroe`s characters first name in the film "Some Like It Hot"?",
           "correct_answer": "Sugar", "incorrect_answers": ["Honey", "Caramel", "Candy"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Velma Kelly and Roxie Hart are the protagonists of which Oscar winning movie?",
           "correct_answer": "Chicago", "incorrect_answers": ["Dreamgirls", "Cabaret", "All That Jazz"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is the name of James Deans character in the 1955 movie "Rebel Without a Cause"?",
           "correct_answer": "Jim Stark", "incorrect_answers": ["Ned Stark", "Jim Kane", "Frank Stark"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is the name of the robot in the 1951 science fiction film classic The Day the Earth Stood Still?",
           "correct_answer": "Gort", "incorrect_answers": ["Robby", "Colossus", "Box"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Who played Batman in the 1997 film "Batman and Robin"?",
           "correct_answer": "George Clooney", "incorrect_answers": ["Michael Keaton", "Val Kilmer", "Christian Bale"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "This movie contains the quote, "I love the smell of napalm in the morning!"",
           "correct_answer": "Apocalypse Now",
           "incorrect_answers": ["Platoon", "The Deer Hunter", "Full Metal Jacket"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In which African country was the 2006 film Blood Diamond mostly set in?",
           "correct_answer": "Sierra Leone",
           "incorrect_answers": ["Liberia", "Burkina Faso", "Central African Republic"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is the name of the first "Star Wars" film by release order?",
           "correct_answer": "A New Hope",
           "incorrect_answers": ["The Phantom Menace", "The Force Awakens", "Revenge of the Sith"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is the name of the Artificial Intelligence system in the 1983 film, "WarGames"?",
           "correct_answer": "War Operation Plan Response",
           "incorrect_answers": ["Self Evolving Thought Helix", "Master Control Program",
                                 "West Campus Analog Computer"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which movie sequel had improved box office results compared to its original film?",
           "correct_answer": "Toy Story 2",
           "incorrect_answers": ["Sin City: A Dame to Kill For", "Speed 2: Cruise Control", "Son of the Mask"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In the 1971 film "Willy Wonka &amp the Chocolate Factory", who played Willy Wonka?",
           "correct_answer": "Gene Wilder", "incorrect_answers": ["Shia LeBouf", "Peter Ostrum", "Johnny Depp"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Who plays the Nemesis in the Resident Evil movies?", "correct_answer": "Matthew Taylor",
           "incorrect_answers": ["Jason Dip", "Eric Mabius", "Jimmy Matts"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In the 1979 British film "Quadrophenia" what is the name of the seaside city the mods are visiting?",
           "correct_answer": "Brighton", "incorrect_answers": ["Eastbourne", "Mousehole", "Bridlington"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "The 1939 movie "The Wizard of Oz" contained a horse that changed color, what material did they use to achieve this effect?",
           "correct_answer": "Gelatin", "incorrect_answers": ["Dye", "Paint", "CGI Effect"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which one of these action movies are shot entirely in one take?", "correct_answer": "Victoria",
           "incorrect_answers": ["Ip Man 2", "The Bourne Legacy", "L&eacuteon: The Professional"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which one of these actors is said to be cut from the film E.T. the Extra-Terrestrial?",
           "correct_answer": "Harrison Ford",
           "incorrect_answers": ["Michael J. Fox", "Andy Kaufman", "Arnold Schwarzenegger"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which movie of film director Stanley Kubrick is known to be an adaptation of a Stephen King novel?",
           "correct_answer": "The Shining",
           "incorrect_answers": ["2001: A Space Odyssey", " Dr. Strangelove ", "Eyes Wide Shut"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What was another suggested name for, the 1985 film, Back to the Future?",
           "correct_answer": "Spaceman From Pluto",
           "incorrect_answers": ["Hill Valley Time Travelers", "The Time Travelers", "The Lucky Man"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is the correct phrase for the Latin saying "Romanes Eunt Domus" in Monty Pythons Life of Brian?",
           "correct_answer": "Romani Ite Domum",
           "incorrect_answers": ["Romans Go Home", "Roxani Ite Domum", "Tomate Ite Domum"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Who played Sgt. Gordon Elias in Platoon (1986)?", "correct_answer": "Willem Dafoe",
           "incorrect_answers": ["Charlie Sheen", "Matt Damon", "Johnny Depp"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Who voices the main character Blu in the 2011 animated film "Rio"?",
           "correct_answer": "Jesse Eisenberg",
           "incorrect_answers": ["Michael Cera", "Jonah Hill", "Zach Galifianakis"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In what year was the movie "Police Academy" released?", "correct_answer": "1984",
           "incorrect_answers": ["1986", "1985", "1983"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Darth Vaders famous reveal to Luke is iconic. But which of these is the right one?",
           "correct_answer": ""No. I am your father."",
           "incorrect_answers": [""Luke, I am your father."",
                                 ""Youre wrong. I am your father."",
                                 ""The truth is that I am your father.""]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What city did the monster attack in the film, "Cloverfield"?",
           "correct_answer": "New York, New York",
           "incorrect_answers": ["Las Vegas, Nevada", "Chicago, Illinois", "Orlando, Florida"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is the correct spelling of the protagonist of the book in The NeverEnding Story (1984)?",
           "correct_answer": "Atreyu", "incorrect_answers": ["Atrayu", "Atraiyu", "Atraeyu"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Who was the director of "Scott Pilgrim vs. the World (2010)"?",
           "correct_answer": "Edgar Wright", "incorrect_answers": ["Phil Lord", "Chris Miller", "Seth Rogan"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which documentary film maker wrote and starred in the film "My Scientology Movie" which first debuted in 2015?",
           "correct_answer": "Louis Theroux", "incorrect_answers": ["Errol Morris", "Joe Berlinger", "Adam Curtis"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In the "Jurassic Park" universe, what is the name of the island that contains InGens Site B?",
           "correct_answer": "Isla Sorna", "incorrect_answers": ["Isla Nublar", "Isla Pena", "Isla Muerta"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In "Jurassic World", which company purchases InGen and creates Jurassic World?",
           "correct_answer": "Masrani Global Corporation ",
           "incorrect_answers": ["Biology Synthetics Technologies", "International Genetics Incorporated",
                                 "International Genetic Technologies"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Who directed the movie "Alien"?", "correct_answer": "Ridley Scott",
           "incorrect_answers": ["Christopher Nolan", "Michael Bay", "James Cameron"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Who plays "Bruce Wayne" in the 2008 movie "The Dark Knight"?",
           "correct_answer": "Christian Bale", "incorrect_answers": ["Michael Caine", "Ron Dean", "Heath Ledger"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which actor plays the character "Tommy Jarvis" in "Friday the 13th: The Final Chapter" (1984)?",
           "correct_answer": "Corey Feldman", "incorrect_answers": ["Macaulay Culkin", "Mel Gibson", "Mark Hamill"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What character in the Winnie the Pooh films was added by Disney and does not appear in the original books?",
           "correct_answer": "Gopher", "incorrect_answers": ["Tigger", "Heffalumps", "Rabbit"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is Lilos last name from Lilo and Stitch?", "correct_answer": "Pelekai",
           "incorrect_answers": ["Anoa\u02bbi", "Kealoha", "Ku\u02bbulei"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In Finding Nemo, what was the name of Nemos mom?", "correct_answer": "Coral",
           "incorrect_answers": ["Sandy", "Pearl", "Shelly"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What film did James Camerons Avatar dethrone as the highest-grossing film ever?",
           "correct_answer": "Titanic", "incorrect_answers": ["Star Wars", "Gone with the Wind", "Jaws"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which 90s comedy cult classic features cameos appearances from Meat Loaf, Alice Cooper and Chris Farley?",
           "correct_answer": "Waynes World",
           "incorrect_answers": ["Bill &amp Teds Excellent Adventure", "Dumb and Dumber",
                                 "Austin Powers: International Man of Mystery"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which star actor was in "Top Gun", "Jerry Maguire" and "Born on the Fourth of July"?",
           "correct_answer": "Tom Cruise", "incorrect_answers": ["Kelly McGillis", "John Travolta", "George Clooney"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In the 2014 film "Birdman", what is the primary instrument in the score?",
           "correct_answer": "Drums", "incorrect_answers": ["Saxophone", "Violin", "Actual Live Birds Singing"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which musical artist had a prominent role in the 2017 film "Kingsman: The Golden Circle"?",
           "correct_answer": "Elton John", "incorrect_answers": ["Lady Gaga", "Rihanna", "Justin Bieber"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is the name of the character Nicolas Cage plays in the movie "National Treasure?"",
           "correct_answer": "Benjamin Franklin Gates",
           "incorrect_answers": ["Thomas Jefferson Walker", "George Washington Swanson", "John Quincy Beckett"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "Which actor plays the role of the main antagonist in the 2011 movie "Tower Heist?"",
           "correct_answer": "Alan Alda", "incorrect_answers": ["Eddie Murphy", "Alec Baldwin", "Kevin Nealon"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "What is the name of the foley artist who designed the famous sounds of Star Wars, including Chewbaccas roar and R2-D2s beeps and whistles?",
           "correct_answer": "Ben Burtt", "incorrect_answers": ["Ken Burns", "Ralph McQuarrie", "Miranda Keyes"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "About how much money did it cost for Tommy Wiseau to make his masterpiece "The Room" (2003)?",
           "correct_answer": "$6 Million", "incorrect_answers": ["$20,000", "$1 Million", "$10 Million"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "The killer in the 1981 film My Bloody Valentine wears what sort of outfit?",
           "correct_answer": "Mining gear", "incorrect_answers": ["Clown costume", "Santa suit", "Police uniform"]},
          {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
           "question": "In the Mad Max franchise, what type of car is the Pursuit Special driven by Max?",
           "correct_answer": "Ford Falcon",
           "incorrect_answers": ["Holden Monaro", "Chrysler Valiant Charger", "Pontiac Firebird"]}]

"""

movies = [{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "The movie \"The Nightmare before Christmas\" was all done with physical objects.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "The film \"2001: A Space Odyssey\" was released on December 31st, 2000.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "In the original script of \"The Matrix\", the machines used humans as additional computing power instead of batteries.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "Samuel L. Jackson had the words, Bad Motherf*cker in-scripted on his lightsaber during the filming of Star Wars.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "In Alfred Hitchcocks film Psycho it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "In the movie The Revenant, DiCaprios character hunts down the killer of his son.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "Brandon Routh plays the titular character in the movie \"John Wick\".",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
                                          {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "George Lucas directed the entire original Star Wars trilogy.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]}]

